name: 'rs-cargo'
description: 'Run cargo command'
author: 'clechasseur'
inputs:
  command:
    description: Cargo command to run (ex. `check` or `build`)
    required: true
  toolchain:
    description: Toolchain to use (without the `+` sign, ex. `nightly`)
    required: false
  args:
    description: Arguments for the cargo command
    required: false
  use-cross:
    description: Use cross instead of cargo
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: package
  color: black
