name: 'rs-cargo'
description: 'Run cargo command'
author: 'clechasseur'
inputs:
  command:
    description: Cargo command to run (ex. `check` or `build`)
    required: true
  toolchain:
    description: Toolchain to use (without the `+` sign, ex. `nightly`)
    required: false
  args:
    description: Arguments for the cargo command
    required: false
  working-directory:
    description: Directory where to perform cargo command
    required: false
  tool:
    description: Tool to use instead of cargo ([`cross`, `cargo-hack`])
    required: false
  cache-key:
    description: Cache key used when using a non-cargo tool
    default: rs-cargo
runs:
  using: 'node24'
  main: 'dist/index.js'
branding:
  icon: package
  color: black
